name: build PDF

on: 
  push:
  pull_request:

permissions:
  contents: read
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: read

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: [self-hosted, Windows]
    timeout-minutes: 5
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: prepare
      shell: powershell
      working-directory: ${{github.workspace}}
      run: |
        function Run-Block-With-Error($block) { \
          $ErrorActionPreference="Stop" \
          Invoke-Command -ScriptBlock $block \
        }

    - name: build PDF
      shell: powershell
      working-directory: ${{github.workspace}}        
      run:
        Run-Block-With-Error {python.exe export_book.py; pdflatex book.tex; bibtex book; pdflatex book.tex; pdflatex book.tex}
    
    #- name: upload PDF
      #working-directory: ${{github.workspace}}
      #uses: actions/upload-artifact@v2
      #with:
       # name: WebApp2
      #path: book.pdf

    - uses: actions/upload-artifact@v3
      with:
        name: upload PDF
        path: book.pdf
